import Porsche_718_Cayman from '../Assets/Cars/Images/718-cayman.webp'
import Porsche_718_Boxster from '../Assets/Cars/Images/718-boxster.webp'
import Porsche_718_Cayman_Style_Edition from '../Assets/Cars/Images/718-cayman-style-edition.webp'
import Porsche_718_Boxster_Style_Edition from '../Assets/Cars/Images/718-boxster-style-edition.webp'
import Porsche_718_Cayman_GTS_4_0 from '../Assets/Cars/Images/718-cayman-gts-4-0.webp'
import Porsche_718_Boxster_GTS_4_0 from '../Assets/Cars/Images/718-boxster-gts-4-0.webp'
import Porsche_718_Cayman_GT4_RS from '../Assets/Cars/Images/718-cayman-gt4-rs.webp'

import Porsche_911_Carrera from '../Assets/Cars/Images/911-carrera.webp'
import Porsche_911_Carrera_T from '../Assets/Cars/Images/911-carrera-t.webp'
import Porsche_911_Carrera_Cabriolet from '../Assets/Cars/Images/911-carrera-cabriolet.webp'
import Porsche_911_Carrera_S from '../Assets/Cars/Images/911-carrera-s.webp'
import Porsche_911_Carrera_S_Cabriolet from '../Assets/Cars/Images/911-carrera-s-cabriolet.webp'
import Porsche_911_Turbo_S from '../Assets/Cars/Images/911-turbo-s.webp'
import Porsche_911_GT3 from '../Assets/Cars/Images/911-gt3.webp'
import Porsche_911_GT3_With_Touring_Package from '../Assets/Cars/Images/911-gt3-with-touring-package.webp'
import Porsche_911_GT3_RS from '../Assets/Cars/Images/911-gt3-rs.webp'
import Porsche_911_S_T from '../Assets/Cars/Images/911-s-t.webp'

import Porsche_Taycan from '../Assets/Cars/Images/taycan.webp'
import Porsche_Taycan_4S from '../Assets/Cars/Images/taycan-4s.webp'
import Porsche_Taycan_4S_Cross_Turismo from '../Assets/Cars/Images/taycan-4s-cross-turismo.webp'
import Porsche_Taycan_GTS from '../Assets/Cars/Images/taycan-gts.webp'
import Porsche_Taycan_Turbo from '../Assets/Cars/Images/taycan-turbo.webp'
import Porsche_Taycan_Turbo_Cross_Turismo from '../Assets/Cars/Images/taycan-turbo-cross-turismo.webp'
import Porsche_Taycan_Turbo_S from '../Assets/Cars/Images/taycan-turbo-s.webp'

import Porsche_Panamera from '../Assets/Cars/Images/panamera.webp'

import Porsche_Macan from '../Assets/Cars/Images/macan.webp'
import Porsche_Macan_S from '../Assets/Cars/Images/macan-s.webp'
import Porsche_Macan_GTS from '../Assets/Cars/Images/macan-gts.webp'

import Porsche_Cayenne from '../Assets/Cars/Images/cayenne.webp'
import Porsche_Cayenne_Coupe from '../Assets/Cars/Images/cayenne-coupe.webp'


export const Cars = [
  {
    name: '718 Cayman',
    header: '718 Models',
    headerIndex: 0,
    image: Porsche_718_Cayman,
    model: '718',
    price: 14772000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 300,
    kws: 220,
    top_speed: 275,
    acceleration: 4.9,
    new: false,
    footnote: false,
  },
  {
    name: '718 Boxster',
    header: '718 Models',
    headerIndex: 0,
    image: Porsche_718_Boxster,
    model: '718',
    price: 15213000,
    body_design: 'Cabriolet',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 300,
    kws: 220,
    top_speed: 275,
    acceleration: 4.9,
    new: false,
    footnote: false,
  },
  {
    name: '718 Cayman Style Edition',
    header: '718 Models',
    headerIndex: 0,
    image: Porsche_718_Cayman_Style_Edition,
    model: '718',
    price: 15568000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 300,
    kws: 220,
    top_speed: 275,
    acceleration: 4.9,
    new: false,
    footnote: false,
  },
  {
    name: '718 Boxster Style Edition',
    header: '718 Models',
    headerIndex: 0,
    image: Porsche_718_Boxster_Style_Edition,
    model: '718',
    price: 16009000,
    body_design: 'Cabriolet',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 300,
    kws: 220,
    top_speed: 275,
    acceleration: 4.9,
    new: false,
    footnote: false,
  },
  {
    name: '718 Cayman GTS 4.0',
    header: '718 Models',
    headerIndex: 0,
    image: Porsche_718_Cayman_GTS_4_0,
    model: '718',
    price: 16751000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 400,
    kws: 294,
    top_speed: 288,
    acceleration: 4.0,
    new: false,
    footnote: false,
  },
  {
    name: '718 Boxster GTS 4.0',
    header: '718 Models',
    headerIndex: 0,
    image: Porsche_718_Boxster_GTS_4_0,
    model: '718',
    price: 17195000,
    body_design: 'Cabriolet',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 400,
    kws: 294,
    top_speed: 288,
    acceleration: 4.0,
    new: false,
    footnote: false,
  },
  {
    name: '718 Cayman GT4 RS',
    header: '718 Cayman GT4 RS',
    headerIndex: 1,
    image: Porsche_718_Cayman_GT4_RS,
    model: '718',
    price: 27443000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 500,
    kws: 368,
    top_speed: 315,
    acceleration: 3.4,
    new: false,
    footnote: false,
  },

  
  {
    name: '911 Carrera',
    header: '911 Carrera & Targa Models',
    headerIndex: 2,
    image: Porsche_911_Carrera,
    model: '911',
    price: 18646000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 385,
    kws: 283,
    top_speed: 293,
    acceleration: 4.2,
    new: false,
    footnote: false,
  },
  {
    name: '911 Carrera T',
    header: '911 Carrera & Targa Models',
    headerIndex: 2,
    image: Porsche_911_Carrera_T,
    model: '911',
    price: 19430000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 385,
    kws: 283,
    top_speed: 291,
    acceleration: 4.0,
    new: false,
    footnote: false,
  },
  {
    name: '911 Carrera Cabriolet',
    header: '911 Carrera & Targa Models',
    headerIndex: 2,
    image: Porsche_911_Carrera_Cabriolet,
    model: '911',
    price: 19732000,
    body_design: 'Cabriolet',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 385,
    kws: 283,
    top_speed: 291,
    acceleration: 4.4,
    new: false,
    footnote: false,
  },
  {
    name: '911 Carrera S',
    header: '911 Carrera & Targa Models',
    headerIndex: 2,
    image: Porsche_911_Carrera_S,
    model: '911',
    price: 20117000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 450,
    kws: 331,
    top_speed: 308,
    acceleration: 307,
    new: false,
    footnote: false,
  },
  {
    name: '911 Carrera S Cabriolet',
    header: '911 Carrera & Targa Models',
    headerIndex: 2,
    image: Porsche_911_Carrera_S_Cabriolet,
    model: '911',
    price: 21792000,
    body_design: 'Cabriolet',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 450,
    kws: 331,
    top_speed: 306,
    acceleration: 3.9,
    new: false,
    footnote: false,
  },
  {
    name: '911 Turbo S',
    header: '911 Turbo Models',
    headerIndex: 3,
    image: Porsche_911_Turbo_S,
    model: '911',
    price: 33536000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Gasoline',
    horsepower: 650,
    kws: 478,
    top_speed: 330,
    acceleration: 2.7,
    new: false,
    footnote: false,
  },
  {
    name: '911 GT3',
    header: '911 GT3 Models',
    headerIndex: 4,
    image: Porsche_911_GT3,
    model: '911',
    price: 27496000,
    body_design: 'Coupe',
    transmission: 'Manual',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 510,
    kws: 375,
    top_speed: 318,
    acceleration: 3.4,
    new: false,
    footnote: false,
  },
  {
    name: '911 GT3 with Touring Package',
    header: '911 GT3 Models',
    headerIndex: 4,
    image: Porsche_911_GT3_With_Touring_Package,
    model: '911',
    price: 27496000,
    body_design: 'Coupe',
    transmission: 'Manual',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 510,
    kws: 375,
    top_speed: 320,
    acceleration: 3.9,
    new: false,
    footnote: false,
  },
  {
    name: '911 GT3 RS',
    header: '911 GT3 RS',
    headerIndex: 5,
    image: Porsche_911_GT3_RS,
    model: '911',
    price: 35056000,
    body_design: 'Coupe',
    transmission: 'PDK',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 525,
    kws: 386,
    top_speed: 296,
    acceleration: 3.2,
    new: false,
    footnote: false,
  },
  {
    name: '911 S/T',
    header: '911 S/T',
    headerIndex: 6,
    image: Porsche_911_S_T,
    model: '911',
    price: 42620000,
    body_design: 'Coupe',
    transmission: 'Manual',
    seats: '2',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: 525,
    kws: 386,
    top_speed: undefined,
    acceleration: undefined,
    new: true,
    footnote: false,
  },

  {
    name: 'Taycan',
    header: 'Taycan Models',
    headerIndex: 7,
    image: Porsche_Taycan,
    model: 'Taycan',
    price: 16093000,
    body_design: 'Sport Saloon',
    transmission: '2-speed transmission',
    seats: '4-5',
    drive: 'RWD',
    fuel_type: 'Electro',
    horsepower: 408,
    kws: 300,
    top_speed: 230,
    acceleration: 5.4,
    new: false,
    footnote: true,
  },
  {
    name: 'Taycan 4S',
    header: 'Taycan Models',
    headerIndex: 7,
    image: Porsche_Taycan_4S,
    model: 'Taycan',
    price: 17535000,
    body_design: 'Sport Saloon',
    transmission: '2-speed transmission',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Electro',
    horsepower: 530,
    kws: 390,
    top_speed: 250,
    acceleration: 4.0,
    new: false,
    footnote: true,
  },
  {
    name: 'Taycan 4S Cross Turismo',
    header: 'Taycan Models',
    headerIndex: 7,
    image: Porsche_Taycan_4S_Cross_Turismo,
    model: 'Taycan',
    price: 18213000,
    body_design: 'Cross Turismo',
    transmission: '2-speed transmission',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Electro',
    horsepower: 571,
    kws: 420,
    top_speed: 240,
    acceleration: 4.1,
    new: false,
    footnote: true,
  },
  {
    name: 'Taycan GTS',
    header: 'Taycan Models',
    headerIndex: 7,
    image: Porsche_Taycan_GTS,
    model: 'Taycan',
    price: 20353000,
    body_design: 'Sport Saloon',
    transmission: '2-speed transmission',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Electro',
    horsepower: 598,
    kws: 440,
    top_speed: 250,
    acceleration: 3.7,
    new: false,
    footnote: true,
  },
  {
    name: 'Taycan Turbo',
    header: 'Taycan Models',
    headerIndex: 7,
    image: Porsche_Taycan_Turbo,
    model: 'Taycan',
    price: 22309000,
    body_design: 'Sport Saloon',
    transmission: '2-speed transmission',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Electro',
    horsepower: 680,
    kws: 500,
    top_speed: 260,
    acceleration: 3.2,
    new: false,
    footnote: true,
  },
  {
    name: 'Taycan Turbo Cross Turismo',
    header: 'Taycan Models',
    headerIndex: 7,
    image: Porsche_Taycan_Turbo_Cross_Turismo,
    model: 'Taycan',
    price: 22500000,
    body_design: 'Cross Turismo',
    transmission: '2-speed transmission',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Electro',
    horsepower: 680,
    kws: 500,
    top_speed: 250,
    acceleration: 3.3,
    new: false,
    footnote: true,
  },
  {
    name: 'Taycan Turbo S',
    header: 'Taycan Models',
    headerIndex: 7,
    image: Porsche_Taycan_Turbo_S,
    model: 'Taycan',
    price: 24372000,
    body_design: 'Sport Saloon',
    transmission: '2-speed transmission',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Electro',
    horsepower: 761,
    kws: 560,
    top_speed: 260,
    acceleration: 2.8,
    new: false,
    footnote: true,
  },
  
  {
    name: 'Panamera',
    header: 'Panamera Models',
    headerIndex: 8,
    image: Porsche_Panamera,
    model: 'Panamera',
    price: 16756000,
    body_design: 'Sport Saloon',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'RWD',
    fuel_type: 'Gasoline',
    horsepower: undefined,
    kws: undefined,
    top_speed: undefined,
    acceleration: undefined,
    new: true,
    footnote: false,
  },
  
  
  {
    name: 'Macan',
    header: 'Macan Models',
    headerIndex: 9,
    image: Porsche_Macan,
    model: 'Macan',
    price: 8806000,
    body_design: 'SUV',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Gasoline',
    horsepower: 265,
    kws: 195,
    top_speed: 232,
    acceleration: 6.4,
    new: false,
    footnote: false,
  },
  {
    name: 'Macan S',
    header: 'Macan Models',
    headerIndex: 9,
    image: Porsche_Macan_S,
    model: 'Macan',
    price: 14352000,
    body_design: 'SUV',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Gasoline',
    horsepower: 380,
    kws: 280,
    top_speed: 256,
    acceleration: 4.8,
    new: false,
    footnote: false,
  },
  {
    name: 'Macan GTS',
    header: 'Macan Models',
    headerIndex: 9,
    image: Porsche_Macan_GTS,
    model: 'Macan',
    price: 15347000,
    body_design: 'SUV',
    transmission: 'PDK',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Gasoline',
    horsepower: 440,
    kws: 324,
    top_speed: 272,
    acceleration: 4.5,
    new: false,
    footnote: false,
  },
  
  {
    name: 'Cayenne',
    header: 'Cayenne Models',
    headerIndex: 10,
    image: Porsche_Cayenne,
    model: 'Cayenne',
    price: 13561000,
    body_design: 'SUV',
    transmission: 'Tiptronic',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Gasoline',
    horsepower: 353,
    kws: 260,
    top_speed: 248,
    acceleration: 6.0,
    new: false,
    footnote: false,
  },
  {
    name: 'Cayenne Coupé',
    header: 'Cayenne Coupé Models',
    headerIndex: 11,
    image: Porsche_Cayenne_Coupe,
    model: 'Cayenne',
    price: 14185000,
    body_design: 'Coupe',
    transmission: 'Tiptronic',
    seats: '4-5',
    drive: 'AWD',
    fuel_type: 'Gasoline',
    horsepower: 440,
    kws: 324,
    top_speed: 272,
    acceleration: 4.5,
    new: false,
    footnote: false,
  }
]
